package com.qualityobjects.springboot.specifications;

public enum FilterOperator {
	LIKE, IN, NOT_IN, NOT_NULL, IS_NULL, EQUAL, NOT_EQUAL, LOWER_THAN, LOWER_THAN_OR_EQUAL, GREATER_THAN, GREATER_THAN_OR_EQUAL,
	IS_MEMBER, IS_NOT_MEMBER,
	EXISTS_EQUALS, EXISTS_LIKE,	
	EXISTS, NOT_EXISTS, ;
}

